=== askubis/RESpecTa/fsautomat.dtd
<!ELEMENT TaskDescription (State+,SubTask*,xi:include*)>
	<!ELEMENT SubTask (State+)>
	

	<!ELEMENT State ((ROBOT|SetOfRobots)?,ECPGeneratorType?,PosX?,PosY?,
	                        (GeneratorParameters|(TrajectoryFilePath,Trajectory))?,taskInit?,
							Speech?,AddArg?,Sensor?,TimeSpan?,Parameters?,transition*)>
		<!ATTLIST State id CDATA #REQUIRED>
		<!ATTLIST State type CDATA #REQUIRED>

	<!ELEMENT PosX (#PCDATA)>
	<!ELEMENT PosY (#PCDATA)>

	<!ELEMENT SetOfRobots (FirstSet)><!--?, SecSet?)>-->
	
	<!ELEMENT FirstSet (ROBOT+)>
	<!--?,<!ELEMENT SecSet (ROBOT+)>-->

	<!ELEMENT ROBOT (#PCDATA)>
	<!ELEMENT ECPGeneratorType (#PCDATA)>
	<!ELEMENT TrajectoryFilePath (#PCDATA)>
	<!ELEMENT Trajectory (Pose+)>
		<!ATTLIST Trajectory coordinateType CDATA #REQUIRED>
		<!ATTLIST Trajectory motionType CDATA #REQUIRED>
		
	<!ELEMENT Pose (StartVelocity,EndVelocity,Velocity,Accelerations,Coordinates)>
		<!ELEMENT StartVelocity (#PCDATA)>
		<!ELEMENT EndVelocity (#PCDATA)>
		<!ELEMENT Velocity (#PCDATA)>
		<!ELEMENT Accelerations (#PCDATA)>
		<!ELEMENT Coordinates (#PCDATA)>
	
	<!ELEMENT taskInit (ecp+,mp?)>
	<!ELEMENT ecp (ecp_gen_t?,ecp_tool_change_gen?,ecp_tff_nose_run_gen?,ecp_tff_rubik_grab_gen?,
		ecp_tff_gripper_approach_gen?,ecp_tff_rubik_face_rotate_gen?,ecp_teach_in_gen?,
		bias_edp_force_gen?,ecp_smooth_gen?,weight_meassure_gen?,ecp_sub_task_gripper_opening?)>
		<!ATTLIST ecp name CDATA #REQUIRED>
		<!ELEMENT ecp_gen_t (#PCDATA)>
		<!ELEMENT ecp_tool_change_gen (#PCDATA)>
		<!ELEMENT ecp_tff_nose_run_gen (#PCDATA)>
		<!ELEMENT ecp_tff_rubik_grab_gen (#PCDATA)>
		<!ELEMENT ecp_tff_gripper_approach_gen (#PCDATA)>
		<!ELEMENT ecp_tff_rubik_face_rotate_gen (#PCDATA)>
		<!ELEMENT ecp_teach_in_gen (#PCDATA)>
		<!ELEMENT bias_edp_force_gen (#PCDATA)>
		<!ELEMENT ecp_smooth_gen (#PCDATA)>
		<!ELEMENT weight_meassure_gen (#PCDATA)>
		<!ELEMENT ecp_sub_task_gripper_opening (#PCDATA)>
	
	<!ELEMENT mp (cube_state?,Sensor*,Transmitter?)>
		<!ELEMENT cube_state (#PCDATA)>
		<!ELEMENT Transmitter (#PCDATA)>
	
	<!ELEMENT Speech (#PCDATA)>
	<!ELEMENT AddArg (#PCDATA)>
	<!ELEMENT Sensor (#PCDATA)>
	<!ELEMENT TimeSpan (#PCDATA)>
	<!ELEMENT GeneratorParameters (#PCDATA)>
	<!ELEMENT Parameters (#PCDATA)>

	<!ELEMENT transition (#PCDATA)>
		<!ATTLIST transition condition CDATA #REQUIRED>
		<!ATTLIST transition target CDATA #REQUIRED>

	<!ELEMENT xi:include (xi:fallback?)>	
	<!ATTLIST xi:include
		xmlns:xi        CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
		href            CDATA       #IMPLIED
		parse           (xml|text)  "xml"
		xpointer        CDATA       #IMPLIED
		encoding        CDATA       #IMPLIED
		accept          CDATA       #IMPLIED
		accept-language CDATA       #IMPLIED
	>
	
	<!ELEMENT xi:fallback ANY>
	<!ATTLIST xi:fallback
        xmlns:xi   CDATA   #FIXED   "http://www.w3.org/2001/XInclude"
    >

=== askubis/RESpecTa/swarm_demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TaskDescription SYSTEM "fsautomat.dtd" >
<TaskDescription>
    <Graphics>
        <PosX>378</PosX>
        <PosY>-1660</PosY>
        <Scale>50</Scale>
    </Graphics>
    <State id="INIT" type="systemInitialization">
        <PosX>-328.000000</PosX>
        <PosY>2400.000000</PosY>
        <taskInit>
            <ecp name="irp6ot_m">
                <ecp_smooth_gen>7</ecp_smooth_gen>
                <bias_edp_force_st>0</bias_edp_force_st>
                <ecp_tff_gripper_approach_gen>8</ecp_tff_gripper_approach_gen>
            </ecp>
            <ecp name="irp6p_m">
                <bias_edp_force_st>0</bias_edp_force_st>
                <ecp_tff_gripper_approach_gen>8</ecp_tff_gripper_approach_gen>
                <ecp_smooth_gen>6</ecp_smooth_gen>
            </ecp>
        </taskInit>
        <transition condition="true" target="approach_1"/>
    </State>
    <State id="approach_1" type="set_next_ecp_state">
        <PosX>1006.000000</PosX>
        <PosY>2228.000000</PosY>
        <ROBOT>irp6p_m</ROBOT>
        <ECPGeneratorType>ECP_GEN_NEWSMOOTH</ECPGeneratorType>
        <TrajectoryFilePath>/home/adam/workspace/mrrocpp/src/application/swarm_demo/trajectory_postument_joint.trj</TrajectoryFilePath>
        <transition condition="true" target="approach_2"/>
    </State>
    <State id="approach_2" type="set_next_ecp_state">
        <PosX>1136.000000</PosX>
        <PosY>2235.000000</PosY>
        <ROBOT>irp6ot_m</ROBOT>
        <ECPGeneratorType>ECP_GEN_NEWSMOOTH</ECPGeneratorType>
        <TrajectoryFilePath>/home/adam/workspace/mrrocpp/src/application/swarm_demo/trajectory_track_joint.trj</TrajectoryFilePath>
        <transition condition="true" target="approach_3"/>
    </State>
    <State id="approach_3" type="wait_for_task_termination">
        <PosX>1284.000000</PosX>
        <PosY>2237.000000</PosY>
        <SetOfRobots>
            <FirstSet>
                <ROBOT>irp6ot_m</ROBOT>
                <ROBOT>irp6p_m</ROBOT>
            </FirstSet>
        </SetOfRobots>
        <transition condition="true" target="bias_post"/>
    </State>
    <State id="bias_post" type="set_next_ecp_state">
        <PosX>1430.000000</PosX>
        <PosY>2239.000000</PosY>
        <ROBOT>irp6p_m</ROBOT>
        <ECPGeneratorType>ECP_ST_BIAS_EDP_FORCE</ECPGeneratorType>
        <AddArg>5</AddArg>
        <TrajectoryFilePath></TrajectoryFilePath>
        <transition condition="true" target="bias_track"/>
    </State>
    <State id="bias_track" type="set_next_ecp_state">
        <PosX>1575.000000</PosX>
        <PosY>2229.000000</PosY>
        <ROBOT>irp6ot_m</ROBOT>
        <ECPGeneratorType>ECP_ST_BIAS_EDP_FORCE</ECPGeneratorType>
        <AddArg>5</AddArg>
        <TrajectoryFilePath></TrajectoryFilePath>
        <transition condition="true" target="wait2"/>
    </State>
    <State id="wait2" type="wait_for_task_termination">
        <PosX>1575.000000</PosX>
        <PosY>2343.000000</PosY>
        <SetOfRobots>
            <FirstSet>
                <ROBOT>irp6ot_m</ROBOT>
                <ROBOT>irp6p_m</ROBOT>
            </FirstSet>
        </SetOfRobots>
        <transition condition="true" target="post1"/>
    </State>
    <State id="post1" type="set_next_ecp_state">
        <PosX>1436.000000</PosX>
        <PosY>2347.000000</PosY>
        <ROBOT>irp6p_m</ROBOT>
        <ECPGeneratorType>ECP_GEN_NEWSMOOTH</ECPGeneratorType>
        <TrajectoryFilePath>/home/adam/workspace/mrrocpp/src/application/swarm_demo/trajectory_postument_angle_p1.trj</TrajectoryFilePath>
        <transition condition="true" target="empty1"/>
    </State>
    <State id="empty1" type="wait_for_task_termination">
        <PosX>1276.000000</PosX>
        <PosY>2359.000000</PosY>
        <SetOfRobots>
            <FirstSet>
                <ROBOT>irp6ot_m</ROBOT>
                <ROBOT>irp6p_m</ROBOT>
            </FirstSet>
        </SetOfRobots>
        <transition condition="true" target="pgrip1"/>
    </State>
    <State id="pgrip1" type="set_next_ecp_state">
        <PosX>1137.000000</PosX>
        <PosY>2351.000000</PosY>
        <ROBOT>irp6p_m</ROBOT>
        <ECPGeneratorType>ECP_GEN_TFF_GRIPPER_APPROACH</ECPGeneratorType>
        <AddArg>0</AddArg>
        <TrajectoryFilePath></TrajectoryFilePath>
        <transition condition="true" target="empty2"/>
    </State>
    <State id="empty2" type="wait_for_task_termination">
        <PosX>1001.000000</PosX>
        <PosY>2344.000000</PosY>
        <SetOfRobots>
            <FirstSet>
                <ROBOT>irp6ot_m</ROBOT>
                <ROBOT>irp6p_m</ROBOT>
            </FirstSet>
        </SetOfRobots>
        <transition condition="true" target="trjoint"/>
    </State>
    <State id="trjoint" type="set_next_ecp_state">
        <PosX>847.000000</PosX>
        <PosY>2347.000000</PosY>
        <ROBOT>irp6ot_m</ROBOT>
        <ECPGeneratorType>ECP_GEN_NEWSMOOTH</ECPGeneratorType>
        <TrajectoryFilePath>/home/adam/workspace/mrrocpp/src/application/swarm_demo/trajectory_track_joint_p1.trj</TrajectoryFilePath>
        <transition condition="true" target="empty3"/>
    </State>
    <State id="empty3" type="wait_for_task_termination">
        <PosX>841.000000</PosX>
        <PosY>2462.000000</PosY>
        <SetOfRobots>
            <FirstSet>
                <ROBOT>irp6ot_m</ROBOT>
                <ROBOT>irp6p_m</ROBOT>
            </FirstSet>
        </SetOfRobots>
        <transition condition="true" target="traa"/>
    </State>
    <State id="traa" type="set_next_ecp_state">
        <PosX>1006.000000</PosX>
        <PosY>2461.000000</PosY>
        <ROBOT>irp6ot_m</ROBOT>
        <ECPGeneratorType>ECP_GEN_NEWSMOOTH</ECPGeneratorType>
        <TrajectoryFilePath>/home/adam/workspace/mrrocpp/src/application/swarm_demo/trajectory_track_angle_p1a.trj</TrajectoryFilePath>
        <transition condition="true" target="empty4"/>
    </State>
    <State id="empty4" type="wait_for_task_termination">
        <PosX>1139.000000</PosX>
        <PosY>2465.000000</PosY>
        <SetOfRobots>
            <FirstSet>
                <ROBOT>irp6ot_m</ROBOT>
                <ROBOT>irp6p_m</ROBOT>
            </FirstSet>
        </SetOfRobots>
        <transition condition="true" target="tr_force"/>
    </State>
    <State id="tr_force" type="set_next_ecp_state">
        <PosX>1293.000000</PosX>
        <PosY>2475.000000</PosY>
        <ROBOT>irp6ot_m</ROBOT>
        <ECPGeneratorType>ECP_GEN_TFF_GRIPPER_APPROACH</ECPGeneratorType>
        <AddArg>0</AddArg>
        <TrajectoryFilePath></TrajectoryFilePath>
        <transition condition="true" target="empty5"/>
    </State>
    <State id="empty5" type="wait_for_task_termination">
        <PosX>1447.000000</PosX>
        <PosY>2470.000000</PosY>
        <SetOfRobots>
            <FirstSet>
                <ROBOT>irp6ot_m</ROBOT>
                <ROBOT>irp6p_m</ROBOT>
            </FirstSet>
        </SetOfRobots>
        <transition condition="true" target="post_angle"/>
    </State>
    <State id="post_angle" type="set_next_ecp_state">
        <PosX>1581.000000</PosX>
        <PosY>2458.000000</PosY>
        <ROBOT>irp6p_m</ROBOT>
        <ECPGeneratorType>ECP_GEN_NEWSMOOTH</ECPGeneratorType>
        <TrajectoryFilePath>/home/adam/workspace/mrrocpp/src/application/swarm_demo/trajectory_postument_angle_p2.trj</TrajectoryFilePath>
        <transition condition="true" target="empty6"/>
    </State>
    <State id="empty6" type="wait_for_task_termination">
        <PosX>1580.000000</PosX>
        <PosY>2603.000000</PosY>
        <SetOfRobots>
            <FirstSet>
                <ROBOT>irp6ot_m</ROBOT>
                <ROBOT>irp6p_m</ROBOT>
            </FirstSet>
        </SetOfRobots>
        <transition condition="true" target="postgrip2"/>
    </State>
    <State id="empty7" type="wait_for_task_termination">
        <PosX>1295.000000</PosX>
        <PosY>2608.000000</PosY>
        <SetOfRobots>
            <FirstSet>
                <ROBOT>irp6ot_m</ROBOT>
                <ROBOT>irp6p_m</ROBOT>
            </FirstSet>
        </SetOfRobots>
        <transition condition="true" target="traa2"/>
    </State>
    <State id="postgrip2" type="set_next_ecp_state">
        <PosX>1440.000000</PosX>
        <PosY>2605.000000</PosY>
        <ROBOT>irp6p_m</ROBOT>
        <ECPGeneratorType>ECP_GEN_TFF_GRIPPER_APPROACH</ECPGeneratorType>
        <AddArg>0</AddArg>
        <TrajectoryFilePath></TrajectoryFilePath>
        <transition condition="true" target="empty7"/>
    </State>
    <State id="traa2" type="set_next_ecp_state">
        <PosX>1142.000000</PosX>
        <PosY>2603.000000</PosY>
        <ROBOT>irp6ot_m</ROBOT>
        <ECPGeneratorType>ECP_GEN_NEWSMOOTH</ECPGeneratorType>
        <TrajectoryFilePath>/home/adam/workspace/mrrocpp/src/application/swarm_demo/trajectory_track_angle_p2.trj</TrajectoryFilePath>
        <transition condition="true" target="empty8"/>
    </State>
    <State id="empty8" type="wait_for_task_termination">
        <PosX>1003.000000</PosX>
        <PosY>2600.000000</PosY>
        <SetOfRobots>
            <FirstSet>
                <ROBOT>irp6ot_m</ROBOT>
                <ROBOT>irp6p_m</ROBOT>
            </FirstSet>
        </SetOfRobots>
        <transition condition="true" target="tr_grip_2"/>
    </State>
    <State id="empty9" type="wait_for_task_termination">
        <PosX>831.000000</PosX>
        <PosY>2721.000000</PosY>
        <SetOfRobots>
            <FirstSet>
                <ROBOT>irp6ot_m</ROBOT>
                <ROBOT>irp6p_m</ROBOT>
            </FirstSet>
        </SetOfRobots>
        <transition condition="true" target="wait2s"/>
    </State>
    <State id="tr_grip_2" type="set_next_ecp_state">
        <PosX>835.000000</PosX>
        <PosY>2599.000000</PosY>
        <ROBOT>irp6ot_m</ROBOT>
        <ECPGeneratorType>ECP_GEN_TFF_GRIPPER_APPROACH</ECPGeneratorType>
        <AddArg>0</AddArg>
        <TrajectoryFilePath></TrajectoryFilePath>
